2025-02-25 17:09:45,109 INFO    MainThread:1022005 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_setup.py:_flush():67] Configure stats pid to 1022005
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_setup.py:_flush():67] Loading settings from /home/jinxulin/.config/wandb/settings
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_setup.py:_flush():67] Loading settings from /home/jinxulin/DAS/ArtBench2/wandb/settings
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/jinxulin/DAS/ArtBench2/wandb/run-20250225_170945-kr3pb43t/logs/debug.log
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/jinxulin/DAS/ArtBench2/wandb/run-20250225_170945-kr3pb43t/logs/debug-internal.log
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_init.py:init():761] calling init triggers
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_init.py:init():784] starting backend
2025-02-25 17:09:45,110 INFO    MainThread:1022005 [wandb_init.py:init():788] sending inform_init request
2025-02-25 17:09:45,123 INFO    MainThread:1022005 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-25 17:09:45,123 INFO    MainThread:1022005 [wandb_init.py:init():803] backend started and connected
2025-02-25 17:09:45,124 INFO    MainThread:1022005 [wandb_init.py:init():896] updated telemetry
2025-02-25 17:09:45,164 INFO    MainThread:1022005 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-25 17:09:48,478 INFO    MainThread:1022005 [wandb_init.py:init():995] starting run threads in backend
2025-02-25 17:09:48,561 INFO    MainThread:1022005 [wandb_run.py:_console_start():2377] atexit reg
2025-02-25 17:09:48,561 INFO    MainThread:1022005 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-25 17:09:48,561 INFO    MainThread:1022005 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-25 17:09:48,561 INFO    MainThread:1022005 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-25 17:09:48,562 INFO    MainThread:1022005 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-25 17:09:48,562 INFO    MainThread:1022005 [wandb_run.py:_config_callback():1261] config_cb None None {'pretrained_model_name_or_path': '../Models/miniSD-diffusers', 'revision': None, 'variant': None, 'dataset_name': 'lambdalabs/naruto-blip-captions', 'dataset_config_name': None, 'train_data_dir': None, 'image_column': 'image', 'caption_column': 'text', 'validation_prompt': 'A naruto with blue eyes.', 'num_validation_images': 4, 'validation_epochs': 1, 'max_train_samples': None, 'output_dir': './finetune/lora/naruto', 'cache_dir': None, 'seed': 1337, 'resolution': 512, 'center_crop': True, 'random_flip': True, 'train_batch_size': 1, 'num_train_epochs': 50, 'max_train_steps': 15000, 'gradient_accumulation_steps': 4, 'gradient_checkpointing': False, 'learning_rate': 0.0001, 'scale_lr': False, 'lr_scheduler': 'cosine', 'lr_warmup_steps': 0, 'snr_gamma': None, 'use_8bit_adam': False, 'allow_tf32': False, 'dataloader_num_workers': 8, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_weight_decay': 0.01, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'push_to_hub': False, 'hub_token': None, 'prediction_type': None, 'hub_model_id': None, 'logging_dir': 'logs', 'mixed_precision': None, 'report_to': 'wandb', 'local_rank': -1, 'checkpointing_steps': 500, 'checkpoints_total_limit': None, 'resume_from_checkpoint': None, 'enable_xformers_memory_efficient_attention': False, 'noise_offset': 0, 'rank': 4}
2025-02-25 17:09:48,836 WARNING MsgRouterThr:1022005 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-25 17:09:48,836 INFO    MsgRouterThr:1022005 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
